# Class: arch_dev
#
# Manage includes of other arch_dev classes
# top-level class for arch_dev ecosystem
#
# WARNING - WARNING - this file is generated by makeinitpp.sh. 
#   any local changes will be overwritten.
#
# Parameters:
#
# Actions:
#   - Include other classes
#
# Requires:
#
# Sample Usage:
#
class arch_dev {
  # Install Android development tools
#  include arch_dev::android

  # Install base packages we want on any (arch) system and setup makepkg.conf
  include arch_dev::arch_base

  # Install augeas, required for some of the puppet classes
  include arch_dev::augeas

  # Install and configure chrony, a roaming/laptop friendly NTP client
#  include arch_dev::chrony

  # Install CUPS printing
#  include arch_dev::cups

  # Install, run and configure DKMS
  include arch_dev::dkms

# BLACKLISTED in makeinitpp.sh: firewall_post
#  # Define firewall rules that will always be at the end of the chain
#  include arch_dev::firewall_post

# BLACKLISTED in makeinitpp.sh: firewall_pre
#  # Define firewall rules that will always be at the beginning of the chain
#  include arch_dev::firewall_pre

  # Install proprietary google-chrome package and ttf-google-fonts-git from archlinuxfr repository.
#  include arch_dev::googlechrome

  # Install iptables and setup framework for puppetlabs/firewall module and set custom rules
#  include arch_dev::iptables

  # Packages largely specific to jantman's workstation setup
#  include arch_dev::jantman_packages

  # Install KDM and KDE basics and run kdm
#  include arch_dev::kde

# BLACKLISTED in makeinitpp.sh: laptop_mode_tools
#  # Install and configute laptop-mode-tools for power saving
#  include arch_dev::laptop_mode_tools

  # Install LibreOffice suite
#  include arch_dev::libreoffice

  # Install the mlocate package and run updatedb
#  include arch_dev::locate

  # Sets up macbook-specific keyboard stuff
#  include arch_dev::mac_keyboard

  # Setup KDM/KDE specific to the MacBook Pro Retina - setup kdmrc
#  include arch_dev::mbp_retina_kde

  # Install mosh (mobile shell) and set firewall rules for it
#  include arch_dev::mosh

  # Install Mozilla ProfileManager for Firefox as an ugly binary untar
#  include arch_dev::mozilla_profilemanager

  # Install and setup networkmanager its KDE components, and ensure dhcpcd is stopped and nm is running
#  include arch_dev::networkmanager

# BLACKLISTED in makeinitpp.sh: nouveau
#  # Install nouveau driver for nvidia graphics and sample xorg.conf. Choose this class OR nvidia.
#  include arch_dev::nouveau

  # Install proprietary nvidia driver for nvidia graphics and sample xorg.conf. Choose this class OR nouveau.
#  include arch_dev::nvidia

  # Install OpenVPN and its NetworkManager part
#  include arch_dev::openvpn

# BLACKLISTED in makeinitpp.sh: pdnsd
#  # Install and configute pdnsd for persistent local dns caching.
#  include arch_dev::pdnsd

  # Install PHP for CLI
#  include arch_dev::php

  # Install and configure profile-sync-daemon - REQUIRES CONFIGURATION
#  include arch_dev::profilesyncdaemon

  # Make /etc/mkinitcpio.d/linux.preset changes for booting via rEFInd
#  include arch_dev::refind

  # Install prerequisites for ruby rvm
#  include arch_dev::rvm

  # Sets up SSD-specific tuning on the system, disks and ext4 partitions
#  include arch_dev::ssd

  # Install and setup OpenSSH, drop in sshd_config
#  include arch_dev::sshd

  # Install sudoers file - Arch default plus allow wheel access to all (with password).
  include arch_dev::sudoers

  # Creates a swap file, makes swap, swapon, update fstab
#  include arch_dev::swapfile

  # Install and configure VirtualBox and Vagrant
#  include arch_dev::virtualbox

  # Install driver for Broadcom BCM4331 wireless, iw and wpa_supplicant
#  include arch_dev::wireless

  # Install packages required for xorg X server
  include arch_dev::xorg

  include arch_dev::gnome

  include arch_dev::gnome-devel

  # Add the archlinuxfr repo to pacman, install yaourt <https://wiki.archlinux.org/index.php/Yaourt> so we can get packages from AUR
#  include arch_dev::yaourt

}
